### ISSUE TITLE
Unable to generate monster

### ISSUE THREAD

**Issue by yuanshengaoshou114** [NotThorny/MobWave#8]
There are no error prompts, challenge prompts are displayed, but no monsters are generated?. The challenge prompt still exists after the stop

05:30:49 <INFO:WorldChallenge> start WorldChallenge: 180
>
The monster has not been generated and there is no follow-up log. Use dockgs3.3

**Comment by NotThorny** [comment]
It looks like this error was caused by a player logging out while the challenge was still active. I've gone ahead and made it so the challenge will end if the player logs out, which should prevent this from occurring again.

[MobWave.zip](https://github.com/NotThorny/MobWave/files/10367637/MobWave.zip)

**Comment by yuanshengaoshou114** [comment]
[Error.txt](https://github.com/NotThorny/MobWave/files/10367967/Error.txt)
This time, there is no hint... the monster has not been generated

> It looks like this error was caused by a player logging out while the challenge was still active. I've gone ahead and made it so the challenge will end if the player logs out, which should prevent this from occurring again.
> 
> [MobWave.zip](https://github.com/NotThorny/MobWave/files/10367637/MobWave.zip)

**Comment by NotThorny** [comment]
It was due to a little error with one of the new checks, I've fixed it.
[MobWave.zip](https://github.com/NotThorny/MobWave/files/10369282/MobWave.zip)
